import { useEffect, useMemo, useState } from "react";
import { CasePackageSchema, type CasePackage } from "@corpwatch/backend/contracts";
import { ChatDrawer } from "./ChatDrawer";
import { OperationsDashboard } from "./OperationsDashboard";
import { StrategyFitChart } from "./StrategyFitChart";

type LoadState = { kind: "loading" } | { kind: "error"; message: string } | { kind: "ready"; data: CasePackage };
const metricLabels: Record<string, string> = { revenue: "Revenue / net sales", gross_profit: "Gross profit", operating_income: "Operating income", sga: "SG&A", restructuring_cost: "Restructuring cost", cash_and_equivalents: "Cash & equivalents", operating_cash_flow: "Operating cash flow", capital_expenditure: "Capital expenditure", inventory: "Inventory", accounts_payable: "Accounts payable", short_term_debt: "Short-term debt", long_term_debt: "Long-term debt", store_count: "Store count", employee_count: "Employee count" };

export function App() {
  const [state, setState] = useState<LoadState>({ kind: "loading" }); const [frameIndex, setFrameIndex] = useState(0); const [chatOpen, setChatOpen] = useState(false);
  useEffect(() => { let active = true; fetch("/demo/case-package.json").then((response) => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }).then((json) => CasePackageSchema.parse(json)).then((data) => { if (active) { setState({ kind: "ready", data }); setFrameIndex(data.replay.length - 1); } }).catch(() => { if (active) setState({ kind: "error", message: "The validated offline case bundle could not be loaded. Run npm run build:case and validate:public-bundle." }); }); return () => { active = false; }; }, []);
  if (state.kind === "loading") return <main className="status-page"><div className="loader" /><p role="status">Loading validated strategic brief…</p></main>;
  if (state.kind === "error") return <main className="status-page"><p className="eyebrow">CorpWatch</p><h1>Bundle unavailable</h1><div role="alert" className="notice">{state.message}</div></main>;
  return <><DashboardNav onOpenAgent={() => setChatOpen(true)} /><ChatDrawer open={chatOpen} onClose={() => setChatOpen(false)} /><Dashboard data={state.data} frameIndex={frameIndex} setFrameIndex={setFrameIndex} onOpenAgent={() => setChatOpen(true)} /></>;
}

function DashboardNav({ onOpenAgent }: { onOpenAgent: () => void }) {
  return <header className="app-nav"><a className="brand" href="#overview" aria-label="CorpWatch dashboard home"><span>CW</span><strong>CorpWatch</strong></a><nav aria-label="Primary navigation"><a href="#overview">Overview</a><a href="#strategy">Strategy</a><a href="#replay">Evidence</a><a href="#metrics">Metrics</a><a href="#operations">Operations</a></nav><button className="agent-button" onClick={onOpenAgent}><span>✦</span> Open Agent</button></header>;
}

function Dashboard({ data, frameIndex, setFrameIndex, onOpenAgent }: { data: CasePackage; frameIndex: number; setFrameIndex: (value: number) => void; onOpenAgent: () => void }) {
  const frame = data.replay[frameIndex]; const visible = useMemo(() => new Set(frame.evidenceIds), [frame]); const blocked = data.readiness.filter((item) => item.status !== "READY"); const decisionsBlocked = blocked.length > 0;
  const formatDate = (value: string) => new Intl.DateTimeFormat("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(value));
  const coverage = Math.min(100, Math.round((new Set(data.metrics.map((item) => item.metricKey)).size / 14) * 100)); const latestEvidence = data.evidence.filter((item) => visible.has(item.id));
  return <main className="dashboard-shell">
    <section id="overview" className="overview-card"><div className="hero-copy"><p className="eyebrow light">Strategic change radar · validated replay</p><h1>{data.company.name}</h1><p className="lede">{data.watchQuestion}</p><div className="hero-actions"><a href="#strategy" className="primary-action">Review strategy</a><button onClick={onOpenAgent} className="secondary-action">Ask evidence agent</button></div></div><div className="posture-card"><span>Recommended posture</span><strong>{data.recommendation.posture}</strong><p>{data.recommendation.rationale}</p><div><small>{frame.stage}</small><small>Index {Math.round(frame.score * 100)}/100</small></div></div></section>
    <section className="snapshot" aria-label="Case snapshot"><article><span>As-of</span><strong>{formatDate(frame.asOf)}</strong></article><article><span>Evidence visible</span><strong>{latestEvidence.length}/{data.evidence.length}</strong></article><article><span>Metric coverage</span><strong>{coverage}%</strong></article><article><span>Decision readiness</span><strong>{decisionsBlocked ? "Blocked" : "Ready"}</strong></article></section>
    <StrategyFitChart data={data} visibleEvidence={visible} blocked={decisionsBlocked} />
    <section id="replay" className="section-block" aria-labelledby="replay-title"><div className="section-heading"><div><p className="eyebrow">Evidence timeline</p><h2 id="replay-title">What was knowable, when</h2><p>{frame.summary}</p></div><label className="date-control">Historical frame<select aria-label="As-of date" value={frameIndex} onChange={(event) => setFrameIndex(Number(event.target.value))}>{data.replay.map((item, index) => <option key={item.asOf} value={index}>{formatDate(item.asOf)}</option>)}</select></label></div>
      {latestEvidence.length === 0 ? <p className="notice">No approved evidence is available for this frame.</p> : <ol className="timeline">{latestEvidence.map((item, index) => <li key={item.id}><div className="timeline-marker"><span>{String(index + 1).padStart(2, "0")}</span></div><article><div className="evidence-meta"><span className="status-pill success">Approved</span><time>{formatDate(item.publiclyAvailableAt)}</time></div><h3 id={`evidence-${item.id}`}>{item.title}</h3><p>{item.excerpt}</p><a href={data.sources.find((source) => source.id === item.sourceId)?.url} target="_blank" rel="noreferrer">Open source <span>↗</span></a></article></li>)}</ol>}
    </section>
    <section id="radar" className="section-block radar-section" aria-labelledby="radar-title"><div className="section-heading"><div><p className="eyebrow">Pattern radar</p><h2 id="radar-title">Why this cluster matters</h2></div></div><div className="insight-grid">{data.claims.filter((claim) => claim.evidenceIds.every((id) => visible.has(id))).slice(0, 3).map((claim, index) => <article className="insight-card" key={claim.id}><span className="insight-number">0{index + 1}</span><p>{claim.text}</p><div>{claim.evidenceIds.map((id) => <a key={id} href={`#evidence-${id}`}>{id}</a>)}</div></article>)}</div></section>
    <section id="metrics" className="section-block" aria-labelledby="metrics-title"><div className="section-heading"><div><p className="eyebrow">Metric lens</p><h2 id="metrics-title">Coverage before conviction</h2><p>Reported observations, normalized units and direct provenance.</p></div><div className="coverage-badge"><strong>{coverage}%</strong><span>coverage</span></div></div>{blocked.length > 0 && <div className="notice" role="status"><strong>Blocked by missing metrics</strong><p>{[...new Set(blocked.flatMap((item) => item.missingMetrics))].map((key) => metricLabels[key]).join(", ")}</p></div>}<div className="table-wrap panel"><table><caption>Reported metric observations</caption><thead><tr><th>Metric</th><th>Value</th><th>Period</th><th>Quality</th><th>Evidence</th></tr></thead><tbody>{data.metrics.map((metric) => <tr key={`${metric.metricKey}-${metric.period}`}><th>{metricLabels[metric.metricKey]}</th><td className="metric-value">{metric.value.toLocaleString()} <small>{metric.unit === "USD_MILLIONS" ? "USD m" : "count"}</small></td><td>{metric.period}</td><td><span className="status-pill success">{metric.quality}</span></td><td><a href={`#evidence-${metric.evidenceId}`}>{metric.evidenceId}</a></td></tr>)}</tbody></table></div></section>
    <OperationsDashboard />
    <section id="agenda" className="section-block" aria-labelledby="agenda-title"><div className="section-heading"><div><p className="eyebrow">Executive agenda</p><h2 id="agenda-title">Decide with a challenger</h2></div></div>{decisionsBlocked ? <div className="notice"><strong>Executive recommendation blocked</strong><p>Collect missing metrics before leadership review.</p></div> : <div className="agenda"><article className="recommendation-card"><span className="tag">Recommended · {data.recommendation.posture}</span><h3>Move deliberately, preserve optionality.</h3><p>{data.recommendation.rationale}</p><p className="evidence-links">Evidence {data.recommendation.evidenceIds.map((id) => <a key={id} href={`#evidence-${id}`}>{id}</a>)}</p></article><article className="challenger-card"><h3>Challenger questions</h3><ol>{data.challengerQuestions.map((question) => <li key={question}>{question}</li>)}</ol></article></div>}</section>
    <footer className="dashboard-footer"><div><strong>CorpWatch</strong><p>Evidence-led strategic decision support.</p></div><div><strong>Northstar Home Retail is fictional.</strong><p>{data.company.comparisonContext}</p></div><div><strong>Methodology</strong><p>{data.limitations.join(" ")}</p></div></footer>
  </main>;
}
