import type { CasePackage, PostureViz, StrategyFitViz, MetricLensViz, EvidenceTimelineViz, PatternRadarViz, OperationsViz } from "@corpwatch/backend/contracts";

export const metricLabels: Record<string, string> = { revenue: "Revenue / net sales", gross_profit: "Gross profit", operating_income: "Operating income", sga: "SG&A", restructuring_cost: "Restructuring cost", cash_and_equivalents: "Cash & equivalents", operating_cash_flow: "Operating cash flow", capital_expenditure: "Capital expenditure", inventory: "Inventory", accounts_payable: "Accounts payable", short_term_debt: "Short-term debt", long_term_debt: "Long-term debt", store_count: "Store count", employee_count: "Employee count" };

export const postureViz = (data: CasePackage): PostureViz => { const frame = data.replay[data.replay.length - 1]; return { kind: "posture", posture: data.recommendation.posture, index: Math.round(frame.score * 100), stage: frame.stage, rationale: data.recommendation.rationale, evidenceIds: data.recommendation.evidenceIds }; };
export const strategyFitViz = (data: CasePackage): StrategyFitViz => ({ kind: "strategyFit", recommended: data.recommendation.posture, scenarios: data.scenarios.map((scenario) => ({ posture: scenario.posture, headline: scenario.headline, score: 35 + 30 + (scenario.posture === data.recommendation.posture ? 25 : 5) + 10, cost: scenario.cost, benefit: scenario.benefit, risk: scenario.risk, impact: scenario.impact })) });
export const metricLensViz = (data: CasePackage): MetricLensViz => ({ kind: "metricLens", coverage: Math.min(100, Math.round((new Set(data.metrics.map((metric) => metric.metricKey)).size / 14) * 100)), metrics: data.metrics.map((metric) => ({ label: metricLabels[metric.metricKey] ?? metric.metricKey, value: metric.value, unit: metric.unit, period: metric.period, quality: metric.quality, evidenceId: metric.evidenceId })) });
export const timelineViz = (data: CasePackage, frame: CasePackage["replay"][number]): EvidenceTimelineViz => ({ kind: "evidenceTimeline", asOf: frame.asOf, items: data.evidence.filter((item) => frame.evidenceIds.includes(item.id)).map((item) => ({ id: item.id, title: item.title, excerpt: item.excerpt, date: item.publiclyAvailableAt, sourceUrl: data.sources.find((source) => source.id === item.sourceId)?.url ?? null, status: "Approved" })) });
export const patternRadarViz = (data: CasePackage): PatternRadarViz => ({ kind: "patternRadar", claims: data.claims.map((claim) => ({ id: claim.id, text: claim.text, evidenceIds: claim.evidenceIds })) });

interface MetricsPayload { summary: { totalRuns: number; validationPassRate: number; averageLatencyMs: number; candidates: number; approved: number }; providerDistribution: Array<{ provider: string; count: number }>; validationTrend: Array<{ at: string; passRate: number; latencyMs: number }> }
export const operationsViz = (metrics: MetricsPayload): OperationsViz => ({ kind: "operations", summary: { totalRuns: metrics.summary.totalRuns, validationPassRate: metrics.summary.validationPassRate, averageLatencyMs: metrics.summary.averageLatencyMs, candidates: metrics.summary.candidates, approved: metrics.summary.approved }, providerDistribution: metrics.providerDistribution, validationTrend: metrics.validationTrend });
